# Generated by Django 2.1 on 2018-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en_us', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_uk_ua', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('text_en_us', models.TextField(null=True, verbose_name='Text')),
                ('text_ru_ru', models.TextField(null=True, verbose_name='Text')),
                ('text_uk_ua', models.TextField(null=True, verbose_name='Text')),
            ],
        ),
    ]
