# Generated by Django 2.1.1 on 2018-09-09 01:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_en_us',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_ru_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
