# Generated by Django 2.1 on 2018-09-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en_us', models.CharField(max_length=255, null=True)),
                ('title_ru_ru', models.CharField(max_length=255, null=True)),
                ('text', models.TextField()),
                ('text_en_us', models.TextField(null=True)),
                ('text_ru_ru', models.TextField(null=True)),
            ],
        ),
    ]
